DECLARE
  NAME_PARAM VARCHAR2(200);
  PHONE_PARAM VARCHAR2(200);
  EMAIL_PARAM VARCHAR2(200);
  v_Return NUMBER;
BEGIN
  NAME_PARAM := 'Max';
  PHONE_PARAM := '06634054';
  EMAIL_PARAM := 'email@gmail.com';

  v_Return := hr.INSERT_CLIENT(
    NAME_PARAM => NAME_PARAM,
    PHONE_PARAM => PHONE_PARAM,
    EMAIL_PARAM => EMAIL_PARAM
  );

END;


SELECT * FROM hr.Clients
