CREATE TABLE hr.BOT_GAME_LOG
(
  ID INTEGER NOT NULL 
, TIME_DATA VARCHAR2(100 CHAR) NOT NULL 
, MESSAGE_TEXT VARCHAR2(200) NOT NULL 
, CONSTRAINT ID_BOT_GAME_LOG_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
